# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20180122_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='view',
            new_name='views',
        ),
    ]
